# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""FidelityModel"""

from abc import ABC, abstractmethod
from collections import Counter
from collections.abc import Hashable
from itertools import chain
from typing import Generic, TypeVar

from qiskit.quantum_info import QubitSparsePauli

from qiskit_noise_learning.gate_sets import GateSet, ModelGateSet
from qiskit_noise_learning.math import IndexedVector
from qiskit_noise_learning.sequences import FidelityIndex, Path

ParameterIndex = TypeVar("ParameterIndex", bound=Hashable)


class FidelityModel(Generic[ParameterIndex], ABC):
    r"""A linear parameterization of the log fidelities of a gate set.

    This class provides an interface into rows of the matrix :math:`A` for which
    :math:`-\log(f) = Ar`, where :math:`f` is the vector of fidelities, and :math:`r` is a reduced
    parameter space.

    Args:
        gate_set: The gate set for which the fidelities are modelled, to be converted to a
            :class:`ModelGateSet`.
    """

    def __init__(self, gate_set: GateSet):
        self._gate_set = gate_set.model_gate_set

    @property
    def gate_set(self) -> ModelGateSet:
        return self._gate_set

    @abstractmethod
    def row_from_fidelity(self, fidelity_index: FidelityIndex) -> IndexedVector[ParameterIndex]:
        """Get a row of the fidelity parameterization matrix.

        Args:
            fidelity_index: The fidelity index for the row.
        """

    def row_from_path(self, path: Path) -> IndexedVector[ParameterIndex]:
        """Get the design matrix row generated by a path.

        If the path is unbound (``depth`` is ``None``), returns the row for the repeatable fragment
        only. If the path is bound (``depth`` is an integer), returns the full row including the
        start and end fragments scaled by the depth.

        Args:
            path: The path.
        """
        vector = IndexedVector[ParameterIndex](dict())

        for fidelity_index in path.repeatable_fragment:
            vector += self.row_from_fidelity(fidelity_index)

        if path.depth is None:
            return vector

        vector = path.depth * vector

        for fidelity_index in chain(path.start_fragment, path.end_fragment):
            vector += self.row_from_fidelity(fidelity_index)

        return vector

    def fidelity_index_latex_str(
        self,
        fidelity_index: FidelityIndex,
        format: str = "transition",
    ) -> str:
        r"""Return a LaTeX string for a fidelity index.

        Args:
            fidelity_index: The fidelity index to label.
            format: Either ``"transition"`` (shows input :math:`\to` output Pauli) or ``"formula"``
                (shows pauli, in_bit_indices, out_bit_indices).

        Returns:
            A LaTeX string.

        Raises:
            ValueError: If ``format`` is not ``"transition"`` or ``"formula"``.
        """
        gate_sym = self._gate_set[fidelity_index.gate_name].latex_str

        if format == "transition":
            in_pauli, out_pauli = fidelity_index.transition
            in_str = _qubit_sparse_pauli_to_latex(in_pauli)
            out_str = _qubit_sparse_pauli_to_latex(out_pauli)
            return rf"{in_str} \xrightarrow{{{gate_sym}}} {out_str}"
        elif format == "formula":
            pauli_str = _qubit_sparse_pauli_to_latex(fidelity_index.pauli)
            parts = [pauli_str]
            if fidelity_index.in_bit_indices:
                in_bits = (
                    r"\{" + ",".join(str(i) for i in sorted(fidelity_index.in_bit_indices)) + r"\}"
                )
                parts.append(rf"b_{{in}}={in_bits}")
            if fidelity_index.out_bit_indices:
                out_bits = (
                    r"\{" + ",".join(str(i) for i in sorted(fidelity_index.out_bit_indices)) + r"\}"
                )
                parts.append(rf"b_{{out}}={out_bits}")
            return rf"f^{{{gate_sym}}}(" + r",\, ".join(parts) + r")"
        else:
            raise ValueError(f"Invalid format: {format!r}. Must be 'transition' or 'index'.")

    def path_latex_str(
        self, path: Path, format: str = "transition", repeatable_only: bool = False
    ) -> str:
        r"""Return a LaTeX string for a path.

        The format shows the repeatable fragment as a bracketed sequence raised to the depth, with
        start and end fragments shown separately if present. In transition format, consecutive
        fidelity indices whose output and input Paulis match are chained into a single arrow
        sequence.

        Args:
            path: The path to label.
            format: The format to use for each fidelity index label. Passed as the
                ``format`` argument to :meth:`fidelity_index_latex_str`.
            repeatable_only: If ``True``, only render the repeatable fragment without brackets
                or depth exponent.

        Returns:
            A LaTeX string.
        """
        if repeatable_only:
            return self._fragment_latex_str(path.repeatable_fragment, format)

        parts = []

        if path.start_fragment:
            parts.append(self._fragment_latex_str(path.start_fragment, format))

        if path.repeatable_fragment:
            rep_str = self._fragment_latex_str(path.repeatable_fragment, format)
            depth_str = str(path.depth) if path.depth is not None else "r"
            parts.append(f"[{rep_str}]^{{{depth_str}}}")

        if path.end_fragment:
            parts.append(self._fragment_latex_str(path.end_fragment, format))

        delimiter = r" \rightarrow " if format == "transition" else ""
        return delimiter.join(parts)

    def _fragment_latex_str(self, fragment: list[FidelityIndex], format: str) -> str:
        """Return a LaTeX string for a single fragment of a path."""
        if format != "transition":
            counts = Counter(fragment)
            parts = []
            seen = set()
            for fi in fragment:
                if fi in seen:
                    continue
                seen.add(fi)
                sym = self.fidelity_index_latex_str(fi, format=format)
                count = counts[fi]
                if count > 1:
                    sym = f"{{{sym}}}^{{{count}}}"
                parts.append(sym)
            return "".join(parts)

        chains = []
        current_chain = []
        for fi in fragment:
            in_pauli, out_pauli = fi.transition
            gate_sym = self._gate_set[fi.gate_name].latex_str
            if current_chain and current_chain[-1][1] == in_pauli:
                current_chain.append((in_pauli, out_pauli, gate_sym))
            else:
                if current_chain:
                    chains.append(current_chain)
                current_chain = [(in_pauli, out_pauli, gate_sym)]
        if current_chain:
            chains.append(current_chain)

        chain_strs = []
        for arrow_chain in chains:
            parts = [_qubit_sparse_pauli_to_latex(arrow_chain[0][0])]
            for _, out_pauli, gate_sym in arrow_chain:
                out_str = _qubit_sparse_pauli_to_latex(out_pauli)
                parts.append(rf"\xrightarrow{{{gate_sym}}} {out_str}")
            chain_strs.append(" ".join(parts))

        return r" \rightarrow ".join(chain_strs)


_PAULI_LABELS = {1: "Z", 2: "X", 3: "Y"}


def _qubit_sparse_pauli_to_latex(pauli: QubitSparsePauli) -> str:
    """Convert a QubitSparsePauli to a LaTeX string like ``X_{0} Z_{2}``."""
    if len(pauli.paulis) == 0:
        return "I"
    parts = []
    for p, idx in zip(pauli.paulis, pauli.indices):
        parts.append(f"{_PAULI_LABELS[int(p)]}_{{{int(idx)}}}")
    return " ".join(parts)
