# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""FidelityModel"""

from abc import ABC, abstractmethod
from collections.abc import Hashable
from itertools import chain
from typing import Generic, TypeVar, overload

import numpy as np

from qiskit_noise_learning.data import ModelData
from qiskit_noise_learning.gate_sets import GateSet, ModelGateSet
from qiskit_noise_learning.math import IndexedVector
from qiskit_noise_learning.sequences import FidelityIndex, Path

ParameterIndex = TypeVar("ParameterIndex", bound=Hashable)


class FidelityModel(Generic[ParameterIndex], ABC):
    r"""A linear parameterization of the log fidelities of a gate set.

    This class provides an interface into rows of the matrix :math:`A` for which
    :math:`-\log(f) = Ar`, where :math:`f` is the vector of fidelities, and :math:`r` is a reduced
    parameter space.

    Args:
        gate_set: The gate set for which the fidelities are modelled, to be converted to a
            :class:`ModelGateSet`.
    """

    def __init__(self, gate_set: GateSet):
        self._gate_set = gate_set.model_gate_set

    @property
    def gate_set(self) -> ModelGateSet:
        return self._gate_set

    @abstractmethod
    def row_from_fidelity(self, fidelity_index: FidelityIndex) -> IndexedVector[ParameterIndex]:
        """Get a row of the log fidelity parameterization matrix.

        Args:
            fidelity_index: The fidelity index for the row.
        """

    def row_from_path(self, path: Path) -> IndexedVector[ParameterIndex]:
        """Get the design matrix row generated by a path.

        If the path is unbound (``depth`` is ``None``), returns the row for the repeatable fragment
        only. If the path is bound (``depth`` is an integer), returns the full row including the
        start and end fragments scaled by the depth.

        Args:
            path: The path.
        """
        vector = IndexedVector[ParameterIndex](dict())

        for fidelity_index in path.repeatable_fragment:
            vector += self.row_from_fidelity(fidelity_index)

        if path.depth is None:
            return vector

        vector = path.depth * vector

        for fidelity_index in chain(path.start_fragment, path.end_fragment):
            vector += self.row_from_fidelity(fidelity_index)

        return vector

    @overload
    def log_fidelity_estimate(self, index: FidelityIndex, model_data: ModelData) -> float: ...

    @overload
    def log_fidelity_estimate(self, index: Path, model_data: ModelData) -> float: ...

    def log_fidelity_estimate(self, index: FidelityIndex | Path, model_data: ModelData) -> float:
        """Return the log-fidelity estimate for a fidelity index or path given model parameters.

        Computes the dot product ``row . params`` where ``row`` is the design matrix row for
        ``index``. For a :class:`~.Path`, the semantics follow :meth:`row_from_path`: unbound paths
        give the per-repetition log-fidelity (repeatable fragment only), bound paths give the total
        log-fidelity including start and end fragments.

        Args:
            index: A fidelity index or path.
            model_data: The fitted model parameters.

        Returns:
            The log-fidelity estimate.

        Raises:
            ValueError: If a parameter index from the design matrix row is not present in
                ``model_data``.
        """
        row = self.row_from_path(index) if isinstance(index, Path) else self.row_from_fidelity(index)

        params = model_data.dataset["parameter_values"]
        param_labels = params.coords["parameter"].values
        param_index_map = {label: pos for pos, label in enumerate(param_labels)}
        param_values = params.values

        dot = 0.0
        for idx, coeff in row.items():
            if idx not in param_index_map:
                raise ValueError(f"Parameter index {idx} not found in ModelData.")
            dot += coeff * param_values[param_index_map[idx]]

        return dot

    @overload
    def fidelity_estimate(self, index: FidelityIndex, model_data: ModelData) -> float: ...

    @overload
    def fidelity_estimate(self, index: Path, model_data: ModelData) -> float: ...

    def fidelity_estimate(self, index: FidelityIndex | Path, model_data: ModelData) -> float:
        """Compute the fidelity estimate for a fidelity index or path given model parameters.

        Returns ``exp(-log_fidelity_estimate(index, model_data))``. See
        :meth:`log_fidelity_estimate` for details on the semantics.

        Args:
            index: A fidelity index or path.
            model_data: The fitted model parameters.

        Returns:
            The fidelity estimate.

        Raises:
            ValueError: If a parameter index from the design matrix row is not present in
                ``model_data``.
        """
        return float(np.exp(-self.log_fidelity_estimate(index, model_data)))
