# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""FidelityModel"""

from abc import abstractmethod
from collections.abc import Hashable
from itertools import chain
from typing import Generic, TypeVar, overload

import numpy as np

from qiskit_noise_learning.data import ModelData
from qiskit_noise_learning.gate_sets import ModelGateSet
from qiskit_noise_learning.math import ComposedLinearMap, IndexedVector, LinearMap
from qiskit_noise_learning.sequences import FidelityIndex, Path

from .fidelity_index_space import FidelityIndexSpace

ParameterIndex = TypeVar("ParameterIndex", bound=Hashable)


class FidelityModel(LinearMap[ParameterIndex, FidelityIndex], Generic[ParameterIndex]):
    r"""A linear parameterization of the log fidelities of a gate set.

    A :class:`FidelityModel` is a :class:`~.LinearMap` whose output space is a
    :class:`~.FidelityIndexSpace`. It represents the matrix :math:`A` for which
    :math:`-\log(f) = Ar`, where :math:`f` is the vector of fidelities and :math:`r` is the
    model parameter vector.

    This is the abstract interface shared by every fidelity model. It collects the domain-level
    behaviour — design-matrix rows for fidelity indices and paths, fidelity estimates, and
    composition — on top of the abstract :meth:`row`. Concrete implementations
    (:class:`~.CompleteFidelityModel`, :class:`~.PauliLindbladModel`, and
    :class:`~.ComposedFidelityModel`) supply their own constructors and set ``self._gate_set``.

    Composition with other :class:`~.LinearMap` instances (via ``@``) returns a
    :class:`~.ComposedFidelityModel` that preserves this interface.
    """

    @property
    def gate_set(self) -> ModelGateSet:
        """The gate set whose fidelities are modelled."""
        return self._gate_set

    @abstractmethod
    def row(self, output_index: FidelityIndex) -> IndexedVector[ParameterIndex]:
        """Get a row of the log fidelity parameterization matrix.

        Args:
            output_index: The fidelity index for the row.
        """

    def compose(self, outer: "LinearMap") -> "LinearMap":
        """Post-compose with a linear map on the output space.

        Since post-composition replaces the output space with ``outer``'s, the result is only a
        fidelity model when ``outer`` maps back into a :class:`~.FidelityIndexSpace`.

        Args:
            outer: A linear map applied after this one.

        Returns:
            A :class:`~.ComposedFidelityModel` if the composed chain still maps into a
            :class:`~.FidelityIndexSpace`, otherwise a plain :class:`~.ComposedLinearMap`.
        """
        outer_maps = outer.maps if isinstance(outer, ComposedLinearMap) else [outer]
        return _composed_fidelity_map([self, *outer_maps])

    def pre_compose(self, inner: "LinearMap") -> "FidelityModel":
        """Pre-compose with a linear map on the input space.

        Pre-composition leaves the output space unchanged, so the result is always a fidelity model.

        Args:
            inner: A linear map applied before this one.

        Returns:
            A :class:`~.ComposedFidelityModel` representing the composition.
        """
        inner_maps = inner.maps if isinstance(inner, ComposedLinearMap) else [inner]
        return _composed_fidelity_map([*inner_maps, self])

    def row_from_fidelity(self, fidelity_index: FidelityIndex) -> IndexedVector[ParameterIndex]:
        """Get a row of the log fidelity parameterization matrix.

        Alias for :meth:`row`.

        Args:
            fidelity_index: The fidelity index for the row.
        """
        return self.row(fidelity_index)

    def row_from_path(self, path: Path) -> IndexedVector[ParameterIndex]:
        """Get the design matrix row generated by a path.

        If the path is unbound (``depth`` is ``None``), returns the row for the repeatable fragment
        only. If the path is bound (``depth`` is an integer), returns the full row including the
        start and end fragments scaled by the depth.

        Args:
            path: The path.
        """
        vector = IndexedVector[ParameterIndex](dict())

        for fidelity_index in path.repeatable_fragment:
            vector += self.row(fidelity_index)

        if path.depth is None:
            return vector

        vector = path.depth * vector

        for fidelity_index in chain(path.start_fragment, path.end_fragment):
            vector += self.row(fidelity_index)

        return vector

    @overload
    def log_fidelity_estimate(self, index: FidelityIndex, model_data: ModelData) -> float: ...

    @overload
    def log_fidelity_estimate(self, index: Path, model_data: ModelData) -> float: ...

    def log_fidelity_estimate(self, index: FidelityIndex | Path, model_data: ModelData) -> float:
        """Return the log-fidelity estimate for a fidelity index or path given model parameters.

        Computes the dot product ``row . params`` where ``row`` is the design matrix row for
        ``index``. For a :class:`~.Path`, the semantics follow :meth:`row_from_path`: unbound paths
        give the per-repetition log-fidelity (repeatable fragment only), bound paths give the total
        log-fidelity including start and end fragments.

        Args:
            index: A fidelity index or path.
            model_data: The fitted model parameters.

        Returns:
            The log-fidelity estimate.

        Raises:
            ValueError: If a parameter index from the design matrix row is not present in
                ``model_data``.
        """
        row = self.row_from_path(index) if isinstance(index, Path) else self.row(index)

        params = model_data.dataset["parameter_values"]
        param_labels = params.coords["parameter"].values
        param_index_map = {label: pos for pos, label in enumerate(param_labels)}
        param_values = params.values

        dot = 0.0
        for idx, coeff in row.items():
            if idx not in param_index_map:
                raise ValueError(f"Parameter index {idx} not found in ModelData.")
            dot += coeff * param_values[param_index_map[idx]]

        return dot

    @overload
    def fidelity_estimate(self, index: FidelityIndex, model_data: ModelData) -> float: ...

    @overload
    def fidelity_estimate(self, index: Path, model_data: ModelData) -> float: ...

    def fidelity_estimate(self, index: FidelityIndex | Path, model_data: ModelData) -> float:
        """Return the fidelity estimate for a fidelity index or path given model parameters.

        Computes ``exp(-log_fidelity_estimate(index, model_data))``. See
        :meth:`log_fidelity_estimate` for details on the semantics.

        Args:
            index: A fidelity index or path.
            model_data: The fitted model parameters.

        Returns:
            The fidelity estimate.
        """
        return float(np.exp(-self.log_fidelity_estimate(index, model_data)))


def _composed_fidelity_map(maps: list[LinearMap]) -> LinearMap:
    """Build the composed map for a flat chain, choosing the type from its output space.

    Returns a :class:`~.ComposedFidelityModel` when the chain maps into a
    :class:`~.FidelityIndexSpace` (so the result is itself a fidelity model), otherwise a plain
    :class:`~.ComposedLinearMap`. The discriminator is the output space of the chain rather than
    the type of any single map, so a :class:`~.ComposedLinearMap` ending in a fidelity model is
    still recognised as a fidelity model.

    Args:
        maps: The flat chain of maps in application order.
    """
    from .composed_fidelity_model import ComposedFidelityModel

    if isinstance(maps[-1].output_space, FidelityIndexSpace):
        return ComposedFidelityModel(maps)
    return ComposedLinearMap(maps)
