# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from typing import Self

import numpy as np
import xarray as xr

from qiskit_noise_learning.sequences import InstructionSequence

from .leveled_data import LeveledData
from .xarray_utils import filter_time, ragged_concat


class RawData(LeveledData):
    """Raw experimental outcome data associated with instruction sequences and classical registers.

    This class is a wrapper around a 1-layer deep XArray ``DataTree`` organized according to the
    number of classical bits generated by the experiments. The keys in the ``DataTree`` are the
    string-cast version of the number of classical bits, and the corresponding dataset contains:
    - Data variables:
        - ``data``: The raw boolean data associated with all measurement data for the experiment,
          with dimensions ``("randomization", "shot", "bit")``.
        - ``data_mask``: A boolean data mask with dimensions ``("randomization", "shot")``. This is
          present to handle potential raggedness in the ``"shot"`` dimension across different
          randomizations.
        - ``measurement_flips``: A boolean array of measurement flips that need to be applied to the
          ``data`` when processing. Has dimensions ``("randomization", "bit")``.
        - ``time_lbs``: Lower bound on data acquisition times, with dimensions
          ``("randomization",)``, and of type ``"datetime64[us]"``.
        - ``time_ubs``: Upper bound on data acquisition times, with dimensions
          ``("randomization",)``, and of type ``"datetime64[us]"``.
    - Coordinates:
        - ``instruction_pattern``: The instruction pattern for the data, along dimension
          ``("randomization",)``, of type :class:`InstructionPattern`.
        - ``depth``: Integer array of depths along dimension ``("randomization",)``.
        - ``creg_bit_boundaries``: Object array of type ``dict``, with keys classical register
          names, and values a tuple ``(start_idx, end_idx)``, such that the bits for that register
          are located in the slice ``start_idx:end_idx`` of the ``"bit"`` dimension. Has dimension
          ``("randomization",)``.

    Assumptions:
    - It is assumed that the bits required to compute the expectation value associated to a given
      :class:`Path` measured by an instruction sequence at the given depth are always at the
      beginning of the ``"bit"`` axis, in the order that they are acquired, and with non-decreasing
      qubit index within each classical register. This assumption ensures expectation value
      computation without the need to look up each register.

    Args:
        datatree: A datatree in the above format.
    """

    def __init__(self, datatree: xr.DataTree):
        self._datatree = datatree

    @property
    def datatree(self) -> xr.DataTree:
        """The data tree."""
        return self._datatree

    @classmethod
    def from_arrays(
        cls,
        instruction_sequences: list[InstructionSequence],
        creg_bit_boundaries: list[dict[str, tuple[int, int]]],
        data: list[np.ndarray[np.bool_]],
        measurement_flips: list[np.ndarray[np.bool_]],
        time_lbs: list[np.ndarray[np.datetime64]],
        time_ubs: list[np.ndarray[np.datetime64]],
    ):
        """Instantiate from data specified as arrays.

        Args:
            instruction_sequences: The list of instruction sequences used to generate the
                experiments.
            creg_bit_boundaries: For each instruction sequence, a dictionary mapping creg name to
                the start and stop indices in the ``"bit"`` dimension of ``data`` and
                ``measurement_flips``. I.e. the data for the the classical register ``creg``
                are ``data[..., creg_bit_boundaries[creg][0]:creg_bit_boundaries[creg][1]]``.
            data: A list of outcome data for each instruction sequence for all classical registers.
                The data has dimensions ``("randomization", "shot", "bit")``. It is assumed that all
                data relevant to :class:`Path` expectation value computation is at the beginning of
                the ``"bit"`` dimension, in the order of acquisition.
            measurement_flips: A list of measurement flips to be applied to the data for each
                instruction sequence. Dimensions are ``("randomization", "bit")``.
            time_lbs: A lower bound on the data collection time for each randomization for a given
                instruction sequence. The dimensions are ``("randomization",)``.
            time_ubs: An upper bound on the data collection time for each randomization for a given
                instruction sequence. The dimensions are ``("randomization",)``.
        """
        raw_data = cls(datatree=xr.DataTree())
        for (
            inst_sequence,
            inst_bit_boundaries,
            inst_data,
            inst_meas_flips,
            inst_time_lbs,
            inst_time_ubs,
        ) in zip(
            instruction_sequences,
            creg_bit_boundaries,
            data,
            measurement_flips,
            time_lbs,
            time_ubs,
        ):
            # create a dataset for a single entry in the lists
            new_dataset = xr.Dataset(
                data_vars={
                    "data": xr.DataArray(data=inst_data, dims=["randomization", "shot", "bit"]),
                    "data_mask": xr.DataArray(
                        data=np.zeros(inst_data.shape[:2], dtype=bool),
                        dims=["randomization", "shot"],
                    ),
                    "measurement_flips": xr.DataArray(
                        data=inst_meas_flips, dims=["randomization", "bit"]
                    ),
                    "time_lbs": xr.DataArray(inst_time_lbs, dims=["randomization"]),
                    "time_ubs": xr.DataArray(inst_time_ubs, dims=["randomization"]),
                },
                coords={
                    "instruction_pattern": (
                        ("randomization",),
                        np.array([inst_sequence.pattern] * len(inst_data), dtype=object),
                    ),
                    "depth": (
                        ("randomization",),
                        np.array([inst_sequence.depth] * len(inst_data), dtype=int),
                    ),
                    "creg_bit_boundaries": (
                        ("randomization",),
                        np.array([inst_bit_boundaries] * len(inst_data), dtype=object),
                    ),
                },
            )

            bit_count = inst_data.shape[-1]
            raw_data = raw_data.merge(cls(xr.DataTree.from_dict({str(bit_count): new_dataset})))

        return raw_data

    def merge(self, other: Self) -> Self:
        """Merge with another raw data set.

        If ``self`` and ``other`` contain data with the same number of cregs, the corresponding
        datasets are concatenated along the ``"randomization"`` dimension. Potential raggedness of
        the ``"shot"`` dimension is handled via the ``"data_mask"`` data variable.

        Args:
            other: The other raw dataset.

        Returns:
            The merged data.
        """

        new_datatree = self.datatree.copy(deep=True)

        for bit_count_str, other_dataset in other.datatree.items():
            if bit_count_str in new_datatree:
                new_datatree[bit_count_str] = ragged_concat(
                    datasets=[new_datatree[bit_count_str].dataset, other_dataset.dataset],
                    concat_dim="randomization",
                    ragged_dim="shot",
                )
            else:
                new_datatree[bit_count_str] = other_dataset

        return RawData(datatree=new_datatree)

    def filter_time(self, lb: np.datetime64, ub: np.datetime64) -> Self:
        """Filter to data gathered within the time bounds.

        Args:
            lb: The time lower bound (inclusive).
            ub: The time upper bound (inclusive).

        Returns:
            The time filtered version of self.
        """
        return RawData(filter_time(self.datatree, lb=lb, ub=ub))
