name: Nightly Dev Tests

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          # Full history needed for copyright year verification in pre-commit
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev,vis,cvxpy]"
          python -m pip install build extremal-python-dependencies==0.1.0
      - name: Build Qiskit SDK development wheel
        run: |
          cd ..
          git clone --filter=tree:0 https://github.com/Qiskit/qiskit
          cd qiskit
          git rev-parse HEAD
          python -m build --wheel
      - name: Pin development versions
        shell: bash
        run: >-
          extremal-python-dependencies pin-dependencies --inplace
          "qiskit @ file:$(echo qiskit/dist/*.whl)"
      - name: Pre-commit checks (linting)
        if: matrix.python-version == '3.13'
        run: |
          pre-commit run --all-files
      - name: Test with pytest
        run: |
          python -m pytest
